feat: валидация двух полей сразу
altiore/form pull request #102
Opened 2021-11-05 17:47 UTC by whitered932

2021-11-05 18:13 UTC, Razzwan requested changes

2021-11-05 18:13 UTC, Razzwan commented on src/@common/types.ts
> +		ref?: any,
Здесь должен быть очень простой механизм, описанный прямо в интерфейсе. Например:
```tsx
export type ValidateFuncType = {
	validate: (
		value: any,
		getFieldValue: (name: string) => any,
	) => {error: Error; value: any} | undefined;
};
```

2021-11-05 18:13 UTC, Razzwan commented on src/create-field/named-field/validated-field/hooks/use-input.ts
> +		return useRef(
хуки нельзя использовать внутри условий

2021-11-05 18:13 UTC, Razzwan commented on src/stories/create-field.stories.tsx
> +		// мы не можем использовать хуки вне компонента :/
Выше описал пример интерфейса

2021-11-06 10:59 UTC, whitered932 commented on src/create-field/named-field/validated-field/hooks/use-input.ts
> +		return useRef(
Почему?

2021-11-06 11:13 UTC, whitered932 commented on src/@common/types.ts
> +		ref?: any,
В моем примере мы передаём formState - он позволяет получить доступ ко всем полям формы и другим данным связанным с ней. Передаваться он обудет только в том случае, если инпут находится в форме. Т.е вне формы мы не сможем использовать данный функционал, что правильно, ведь могут быть конфликты имён. А тут мы будем пользователю возвращать функцию для получение значения поля по имени - так может ему это и не нужно? Лучше передать состояние формы и для него это будет удобнее. Расширяется спект возможностей

2021-11-14 08:56 UTC, closed without merging