feat(docs): added Field usage description
altiore/form pull request #114
Opened 2021-11-16 07:57 UTC by QraisinQ

2021-11-16 09:47 UTC, Razzwan requested changes

2021-11-16 09:47 UTC, Razzwan commented on src/docs/create-field.md
> +	const Field = createField(
Это независимый компонент, а не часть страницы

2021-11-16 09:47 UTC, Razzwan commented on src/docs/create-field.ru.md
> +**Чтобы создать простое поле вне формы, необходимо импортировать createField из '@altiore/form', а затем использовать Field с обязательным параметром name = 'YourFieldName'**
1. Слово "простое" нужно удалить. Мы создаем поле.

2. Не нужно подчеркивать, что мы создаем поле ВНЕ формы - это не имеет смысла. Мы просто создаем поле (можем создать вне формы, а можем и внутри формы)

Текст: "Создание поля ввода:"

2021-11-16 09:47 UTC, Razzwan commented on src/docs/create-field.ru.md
> +			/* you can add any extra fields here: */ label,
Здесь текст на русском языке должен быть

2021-11-17 09:01 UTC, Razzwan approved these changes

2021-11-17 09:04 UTC, Razzwan requested changes

2021-11-17 09:04 UTC, Razzwan commented on src/docs/create-field.md
> +		errors,
В простейшем примере лучше использовать строковое поле `error` вместо `errors`

2021-11-17 09:04 UTC, Razzwan commented on src/docs/create-field.md
> +		inputRef,
В простейшем примере не нужно использовать `inputRef` - удалить

2021-11-17 09:04 UTC, Razzwan commented on src/docs/create-field.md
> +				<span>{errors[0]}</span>
Строковое поле `error` вместо массива здесь

2021-11-17 09:04 UTC, Razzwan commented on src/docs/create-field.md
> +					<input id="input-id" name={name} ref={inputRef} />
inputRef удалить

2021-11-17 09:19 UTC, QraisinQ commented on src/docs/create-field.ru.md
> +**Чтобы создать простое поле вне формы, необходимо импортировать createField из '@altiore/form', а затем использовать Field с обязательным параметром name = 'YourFieldName'**
Описание расширить?

2021-11-17 09:37 UTC, Razzwan requested changes

2021-11-17 09:37 UTC, Razzwan commented on src/docs/create-field.md
> +				<span>{errors}</span>
Ошибка

2021-11-17 09:46 UTC, merged