Translation
altiore/form pull request #162
Opened 2022-01-14 09:42 UTC by QraisinQ

2022-01-14 10:13 UTC, Razzwan requested changes

2022-01-16 13:31 UTC, QraisinQ commented
https://user-images.githubusercontent.com/74140853/149662049-a87020d5-7114-40c6-9a87-683815cde25e.mp4

2022-01-16 13:33 UTC, QraisinQ commented on package.json
> +		"bootstrap-icons": "^1.7.2",
Удалил

2022-01-16 13:33 UTC, QraisinQ commented on src/stories/field-array/field-array.tsx
> +					<svg
С картинками остался вопрос открытым:  не понимаю пока, почему они не отображаются

2022-01-16 18:49 UTC, Razzwan requested changes

2022-01-16 18:49 UTC, Razzwan commented on src/stories/field-array/field-array.tsx
> +				<form className="shadow border border-secondary rounded-3 mb-3 p-3">
Здесь не должно быть элемента формы, ведь это инпут, который должен всегда находиться внутри формы. Можно использовать обычный div вместо этого

2022-01-16 18:49 UTC, Razzwan commented on src/stories/field-array/field-array.tsx
> +				<form className="shadow border border-secondary rounded-3 mb-3 p-3">
То же самое, используй div вместо form

2022-01-16 18:49 UTC, Razzwan commented on src/stories/field-array/field-array.tsx
> +				<form className="shadow border border-secondary rounded-3 mb-3 p-3">
То же самое. Используй div вместо формы

2022-01-16 18:49 UTC, Razzwan commented on src/stories/field-array/field-array.tsx
> +					<form className="shadow border border-secondary rounded-3 mb-3 p-3 w-75">
То же самое, Используй div вместо формы

2022-01-17 10:11 UTC, Razzwan approved these changes

2022-01-17 10:20 UTC, Razzwan approved these changes

2022-01-18 21:19 UTC, Razzwan approved these changes

2022-01-18 21:19 UTC, merged