feat: find iputs with same name
altiore/form pull request #9
Opened 2021-10-01 12:22 UTC by CptKokao

2021-10-01 21:11 UTC, Razzwan requested changes

2021-10-01 21:11 UTC, Razzwan commented on src/field/field.tsx
> +	const handleDebounceFn = (e: Event) => {
Не стоит убирать `useCallback` здесь. Лучше верни как было

2021-10-01 21:11 UTC, Razzwan commented on src/field/field.tsx
> +	const debounceHandle = _debounce(handleDebounceFn, 1500);
1. Погугли использование дебьенса с useCallback - там есть хороший пример и описание, как именно это должно работать и почему. useCallback нужен
2. Т.к. мы собираемся использовать событие `blur` (описано ниже), то задержку нужно уменьшить до 200 миллисекунд

2021-10-01 21:11 UTC, Razzwan commented on src/field/field.tsx
> +		const inputs = document.querySelectorAll(`input[name=${name}]`);
Используй `ref` для фрагмента, чтоб найти правильный инпут

2021-10-01 21:11 UTC, Razzwan commented on src/field/field.tsx
> +					currentInput.addEventListener('keyup', handleKeyUp);
Подписывайся на событие `blur` вместо `keyup`. Мы пока слишком далеко от необходимости использовать `keyup` и нам нужно простейшее рабочее решение

2021-10-01 21:11 UTC, Razzwan commented on src/field/field.tsx
> +			if (validate && currentInput) {
Создай переменную `const isShouldSubscribeValidateEvent = Boolean(input && validate)` выше и переиспользуй ее дважды

2021-10-04 11:14 UTC, CptKokao commented on src/field/field.tsx
> +			if (validate && currentInput) {
Такое условие не будет правильно работать, потому что есть вариант, где validate не будет передан и тогда будет ошибка `Error(`Input c name=${name} не был найден`)`. Поэтому, нам нужно отдельно проверять input и только потом validate.

2021-10-04 11:19 UTC, CptKokao commented on src/field/field.tsx
> +		const inputs = document.querySelectorAll(`input[name=${name}]`);
ref возвращает null для React.Fragment, поэтому пока использовал `<span>`

В том примере, что тебе удалось найти во время совещания, в консоле ошибки, видимо пример тестовый.
![image](https://user-images.githubusercontent.com/30856643/135842501-3639dc20-6ec2-403a-8108-2a635ceec4a4.png)

2021-10-04 11:19 UTC, CptKokao commented on src/field/field.tsx
> +	const handleDebounceFn = (e: Event) => {
Вернул

2021-10-04 11:21 UTC, CptKokao commented on src/field/field.tsx
> +	const debounceHandle = _debounce(handleDebounceFn, 1500);
1. Вернул
2. Добавил 200 миллисекунд

2021-10-04 12:40 UTC, merged